# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dcd_regeditor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 844)
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1055, 771))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label_5.setMinimumSize(QtCore.QSize(70, 0))
        self.label_5.setObjectName("label_5")
        self.comboBox_ProjectName = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_ProjectName.setGeometry(QtCore.QRect(80, 45, 131, 20))
        self.comboBox_ProjectName.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_ProjectName.setEditable(True)
        self.comboBox_ProjectName.setObjectName("comboBox_ProjectName")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(15, 15, 70, 23))
        self.label_4.setMinimumSize(QtCore.QSize(70, 0))
        self.label_4.setObjectName("label_4")
        self.comboBox_Category = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Category.setGeometry(QtCore.QRect(80, 15, 131, 20))
        self.comboBox_Category.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_Category.setObjectName("comboBox_Category")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(270, 15, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_IpRepo = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_IpRepo.setGeometry(QtCore.QRect(355, 15, 221, 20))
        self.lineEdit_IpRepo.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_IpRepo.setObjectName("lineEdit_IpRepo")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 45, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_Library = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Library.setGeometry(QtCore.QRect(355, 45, 221, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Library.sizePolicy().hasHeightForWidth())
        self.lineEdit_Library.setSizePolicy(sizePolicy)
        self.lineEdit_Library.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_Library.setObjectName("lineEdit_Library")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_13.setGeometry(QtCore.QRect(615, 45, 101, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.lineEdit_WorkFolder = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_WorkFolder.setGeometry(QtCore.QRect(725, 45, 300, 20))
        self.lineEdit_WorkFolder.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_WorkFolder.setObjectName("lineEdit_WorkFolder")
        self.label_logo_fh = QtWidgets.QLabel(self.groupBox)
        self.label_logo_fh.setGeometry(QtCore.QRect(855, 5, 171, 31))
        self.label_logo_fh.setObjectName("label_logo_fh")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.stackedWidget = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidgetPage1 = QtWidgets.QWidget()
        self.stackedWidgetPage1.setObjectName("stackedWidgetPage1")
        self.tabWidget = QtWidgets.QTabWidget(self.stackedWidgetPage1)
        self.tabWidget.setGeometry(QtCore.QRect(0, 5, 1031, 681))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_RegBlock = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_RegBlock.setGeometry(QtCore.QRect(5, 40, 1016, 621))
        self.tableWidget_RegBlock.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_RegBlock.setDragEnabled(True)
        self.tableWidget_RegBlock.setDragDropOverwriteMode(True)
        self.tableWidget_RegBlock.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget_RegBlock.setDefaultDropAction(QtCore.Qt.TargetMoveAction)
        self.tableWidget_RegBlock.setAlternatingRowColors(True)
        self.tableWidget_RegBlock.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tableWidget_RegBlock.setRowCount(100)
        self.tableWidget_RegBlock.setColumnCount(6)
        self.tableWidget_RegBlock.setObjectName("tableWidget_RegBlock")
        self.tableWidget_RegBlock.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_RegBlock.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget_RegBlock.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget_RegBlock.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_RegBlock.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget_RegBlock.verticalHeader().setMinimumSectionSize(20)
        self.tableWidget_RegBlock.verticalHeader().setSortIndicatorShown(True)
        self.tableWidget_RegBlock.verticalHeader().setStretchLastSection(False)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 15, 46, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(65, 15, 46, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(115, 15, 46, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_8.setGeometry(QtCore.QRect(165, 15, 46, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.spinBox_NumRegs = QtWidgets.QSpinBox(self.tab)
        self.spinBox_NumRegs.setGeometry(QtCore.QRect(325, 15, 37, 21))
        self.spinBox_NumRegs.setMinimum(1)
        self.spinBox_NumRegs.setMaximum(64)
        self.spinBox_NumRegs.setProperty("value", 8)
        self.spinBox_NumRegs.setObjectName("spinBox_NumRegs")
        self.lineEdit_EntityName = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_EntityName.setGeometry(QtCore.QRect(455, 15, 116, 20))
        self.lineEdit_EntityName.setObjectName("lineEdit_EntityName")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(595, 15, 91, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(705, 15, 91, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(240, 15, 86, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(385, 15, 81, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab)
        self.pushButton_17.setGeometry(QtCore.QRect(820, 15, 91, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab)
        self.pushButton_18.setGeometry(QtCore.QRect(930, 15, 91, 23))
        self.pushButton_18.setObjectName("pushButton_18")
        self.tabWidget.addTab(self.tab, "")
        self.CreateTestbench = QtWidgets.QWidget()
        self.CreateTestbench.setObjectName("CreateTestbench")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.CreateTestbench)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.CreateTestbench)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 1000, 641))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_4.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_4.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_4.setMinimumSize(QtCore.QSize(1000, 0))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.tableWidget_Testbench = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_4)
        self.tableWidget_Testbench.setGeometry(QtCore.QRect(0, 50, 1000, 546))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_Testbench.sizePolicy().hasHeightForWidth())
        self.tableWidget_Testbench.setSizePolicy(sizePolicy)
        self.tableWidget_Testbench.setMinimumSize(QtCore.QSize(1000, 0))
        self.tableWidget_Testbench.setAlternatingRowColors(True)
        self.tableWidget_Testbench.setRowCount(40)
        self.tableWidget_Testbench.setColumnCount(60)
        self.tableWidget_Testbench.setObjectName("tableWidget_Testbench")
        self.tableWidget_Testbench.verticalHeader().setDefaultSectionSize(25)
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 600, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_10.setGeometry(QtCore.QRect(415, 600, 75, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_11.setGeometry(QtCore.QRect(335, 600, 75, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_12.setGeometry(QtCore.QRect(545, 600, 106, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_14.setGeometry(QtCore.QRect(690, 600, 75, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_15.setGeometry(QtCore.QRect(765, 10, 75, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_16.setGeometry(QtCore.QRect(855, 10, 75, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.lineEdit_SbusOffset = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_SbusOffset.setGeometry(QtCore.QRect(560, 15, 113, 20))
        self.lineEdit_SbusOffset.setObjectName("lineEdit_SbusOffset")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_3.setGeometry(QtCore.QRect(465, 15, 96, 16))
        self.label_3.setObjectName("label_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_4.addWidget(self.scrollArea_3)
        self.tabWidget.addTab(self.CreateTestbench, "")
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.stackedWidgetPage2 = QtWidgets.QWidget()
        self.stackedWidgetPage2.setObjectName("stackedWidgetPage2")
        self.stackedWidget.addWidget(self.stackedWidgetPage2)
        self.stackedWidgetPage3 = QtWidgets.QWidget()
        self.stackedWidgetPage3.setObjectName("stackedWidgetPage3")
        self.stackedWidget.addWidget(self.stackedWidgetPage3)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1075, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_ProjectName.currentIndexChanged['int'].connect(MainWindow.onCmd_SelectProject)
        self.pushButton_3.clicked.connect(MainWindow.onCmd_SaveRegBlock)
        self.pushButton_4.clicked.connect(MainWindow.onCmd_RegBlockInsertRow)
        self.pushButton_6.clicked.connect(MainWindow.onCmd_RegBlockDeleteRow)
        self.pushButton_7.clicked.connect(MainWindow.onCmd_RegBlockRowUp)
        self.pushButton_8.clicked.connect(MainWindow.onCmd_RegBlockRowDown)
        self.pushButton_5.clicked.connect(MainWindow.onCmd_GenerateRegBlock)
        self.pushButton_2.clicked.connect(MainWindow.onCmd_SelectLibrary)
        self.pushButton_9.clicked.connect(MainWindow.onCmd_SignalsToTestbench)
        self.pushButton_10.clicked.connect(MainWindow.onCmd_SaveStimuli)
        self.pushButton_11.clicked.connect(MainWindow.onCmd_LoadStimuli)
        self.pushButton_12.clicked.connect(MainWindow.onCmd_GenerateTB)
        self.comboBox_Category.currentIndexChanged['QString'].connect(MainWindow.onCmd_SelectCategory)
        self.pushButton.clicked.connect(MainWindow.onCmd_SelectRepository)
        self.pushButton_13.clicked.connect(MainWindow.onCmd_SelectWorkFolder)
        self.pushButton_14.clicked.connect(MainWindow.onCmd_ViewTB)
        self.pushButton_15.clicked.connect(MainWindow.onCmd_InsertTS)
        self.pushButton_16.clicked.connect(MainWindow.onCmd_DeleteTS)
        self.pushButton_17.clicked.connect(MainWindow.onCmd_ViewCodeTemplate)
        self.pushButton_18.clicked.connect(MainWindow.onCmd_ViewGeneratedCode)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Project Name"))
        self.label_4.setText(_translate("MainWindow", "Category"))
        self.pushButton.setText(_translate("MainWindow", "Repository"))
        self.pushButton_2.setText(_translate("MainWindow", "Library"))
        self.pushButton_13.setText(_translate("MainWindow", "MSIM work folder"))
        self.label_logo_fh.setText(_translate("MainWindow", "logo_fh"))
        self.tableWidget_RegBlock.setSortingEnabled(True)
        self.pushButton_4.setText(_translate("MainWindow", "Insert"))
        self.pushButton_6.setText(_translate("MainWindow", "Delete"))
        self.pushButton_7.setText(_translate("MainWindow", "Up"))
        self.pushButton_8.setText(_translate("MainWindow", "Down"))
        self.lineEdit_EntityName.setText(_translate("MainWindow", "registers"))
        self.pushButton_3.setText(_translate("MainWindow", "Save RegBlock"))
        self.pushButton_5.setText(_translate("MainWindow", "Generate"))
        self.label.setText(_translate("MainWindow", "No. of Registers"))
        self.label_2.setText(_translate("MainWindow", "Entity Name:"))
        self.pushButton_17.setText(_translate("MainWindow", "View Template"))
        self.pushButton_18.setText(_translate("MainWindow", "View gen. Code"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Edit Registers"))
        self.pushButton_9.setText(_translate("MainWindow", "GetSignals"))
        self.pushButton_10.setText(_translate("MainWindow", "Save Stimuli"))
        self.pushButton_11.setText(_translate("MainWindow", "Read Stimuli"))
        self.pushButton_12.setText(_translate("MainWindow", "Generate TB cmd"))
        self.pushButton_14.setText(_translate("MainWindow", "View TB cmd"))
        self.pushButton_15.setText(_translate("MainWindow", "Insert TS"))
        self.pushButton_16.setText(_translate("MainWindow", "Delete TS"))
        self.label_3.setText(_translate("MainWindow", "SBUS offset (HEX)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CreateTestbench), _translate("MainWindow", "Create Testbench"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

