# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Yoshi/OneDrive - FH JOANNEUM/FH/02_Master/1. Semester/02_MIC/Lab/03+04/LED_IRQ/LED_IRQ.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
# IP: The module: 'design_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Yoshi/OneDrive - FH JOANNEUM/FH/02_Master/1. Semester/02_MIC/Lab/03+04/LED_IRQ/LED_IRQ.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Yoshi/OneDrive - FH JOANNEUM/FH/02_Master/1. Semester/02_MIC/Lab/03+04/LED_IRQ/LED_IRQ.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
# IP: The module: 'design_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Yoshi/OneDrive - FH JOANNEUM/FH/02_Master/1. Semester/02_MIC/Lab/03+04/LED_IRQ/LED_IRQ.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
