<?xml version="1.0" encoding="ASCII"?>
<ResourceModel:App xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ResourceModel="http://www.infineon.com/Davex/Resource.ecore" name="ENCODER_POSIF" URI="http://resources/4.0.6/app/ENCODER_POSIF/0" description="APP gets the motor position and&#xA;speed using  incremental encoder." mode="NOTSHARABLE" version="4.0.6" minDaveVersion="4.0.0" instanceLabel="ENCODER_POSIF_0" appLabel="" containingProxySignal="true">
  <properties provideInit="true"/>
  <virtualSignals name="phase_a" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_input0" hwSignal="ipos0" hwResource="//@hwResources.4" visible="true"/>
  <virtualSignals name="phase_b" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_input1" hwSignal="ipos1" hwResource="//@hwResources.4" visible="true"/>
  <virtualSignals name="index" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_input2" hwSignal="ipos2" hwResource="//@hwResources.4" required="false"/>
  <virtualSignals name="event_index_signal" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_idxe" hwSignal="indxe" hwResource="//@hwResources.4" required="false" visible="true"/>
  <virtualSignals name="event_phase_error_signal" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_erre" hwSignal="erre" hwResource="//@hwResources.4" visible="true"/>
  <virtualSignals name="event_qclock_signal" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_cnte" hwSignal="cnte" hwResource="//@hwResources.4" visible="true"/>
  <virtualSignals name="event_direction_change_signal" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_dire" hwSignal="dire" hwResource="//@hwResources.4" visible="true"/>
  <virtualSignals name="event_period_clock_signal" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pclke" hwSignal="pcle" hwResource="//@hwResources.4" visible="true"/>
  <virtualSignals name="quadrature_clock" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_out0" hwSignal="out0" hwResource="//@hwResources.4"/>
  <virtualSignals name="quadrature_direction" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_out1" hwSignal="out1" hwResource="//@hwResources.4"/>
  <virtualSignals name="period_clock" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_out2" hwSignal="out2" hwResource="//@hwResources.4" visible="true"/>
  <virtualSignals name="index_signal" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_out3" hwSignal="out3" hwResource="//@hwResources.4" required="false" visible="true"/>
  <virtualSignals name="index_count" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_out4" hwSignal="out4" hwResource="//@hwResources.4" required="false" visible="true"/>
  <virtualSignals name="syncstart" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_out5" hwSignal="out5" hwResource="//@hwResources.4" visible="true"/>
  <virtualSignals name="phase_a_pad" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_ph_a" hwSignal="pad" hwResource="//@hwResources.0" visible="true"/>
  <virtualSignals name="phase_b_pad" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_ph_b" hwSignal="pad" hwResource="//@hwResources.1" visible="true"/>
  <virtualSignals name="index_pad" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_idx" hwSignal="pad" hwResource="//@hwResources.2" required="false"/>
  <virtualSignals name="encoder_enable_pad" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_enenc" hwSignal="pad" hwResource="//@hwResources.3"/>
  <virtualSignals name="position_counter_slice_global_signal" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_slice0_globalsignal" hwSignal="global_signal" hwResource="//@hwResources.5"/>
  <virtualSignals name="revolution_counter_slice_global_signal" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_slice1_globalsignal" hwSignal="global_signal" hwResource="//@hwResources.6" required="false"/>
  <virtualSignals name="time_capture_slice_global_signal" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_slice2_globalsignal" hwSignal="global_signal" hwResource="//@hwResources.7"/>
  <virtualSignals name="timestamp_triggerslice_global_signal" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_slice3_globalsignal" hwSignal="global_signal" hwResource="//@hwResources.8"/>
  <virtualSignals name="sr_timestamp_trigger_periodmatch" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_triggen_pm_nvicsignal_in" hwSignal="signal_in" hwResource="//@hwResources.15" required="false" visible="true"/>
  <virtualSignals name="event_timestamp_trigger_period_match" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu43_pmus_omds" hwSignal="pmus_omds" hwResource="//@hwResources.8" required="false" visible="true"/>
  <virtualSignals name="event_revolution_counter_overflow" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu41_pmus_omds" hwSignal="pmus_omds" hwResource="//@hwResources.6" required="false" visible="true"/>
  <virtualSignals name="phase_a_event_generation_signal_a" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventgen_input_a_ph_a" hwSignal="a" hwResource="//@hwResources.9" required="false"/>
  <virtualSignals name="phase_b_event_generation_signal_a" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventgen_input_a_ph_b" hwSignal="a" hwResource="//@hwResources.10" required="false"/>
  <virtualSignals name="index_event_generation_signal_a" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventgen_input_a_idx" hwSignal="a" hwResource="//@hwResources.11" required="false"/>
  <virtualSignals name="phase_a_event_generation_flag_status" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventgen_flagstatus_ph_a" hwSignal="fl" hwResource="//@hwResources.9" required="false"/>
  <virtualSignals name="phase_b_event_generation_flag_status" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventgen_flagstatus_ph_b" hwSignal="fl" hwResource="//@hwResources.10" required="false"/>
  <virtualSignals name="index_event_generation_flag_status" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventgen_flagstatus_idx" hwSignal="fl" hwResource="//@hwResources.11" required="false"/>
  <virtualSignals name="phase_a_event_detection_in" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventdet_pdin_ph_a" hwSignal="pdin" hwResource="//@hwResources.12" required="false"/>
  <virtualSignals name="phase_b_event_detection_in" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventdet_pdin_ph_b" hwSignal="pdin" hwResource="//@hwResources.13" required="false"/>
  <virtualSignals name="index_event_detection_in" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventdet_pdin_idx" hwSignal="pdin" hwResource="//@hwResources.14" required="false"/>
  <virtualSignals name="phase_a_event_detection_out" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventdet_pdout_ph_a" hwSignal="pdout" hwResource="//@hwResources.12" required="false"/>
  <virtualSignals name="phase_b_event_detection_out" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventdet_pdout_ph_b" hwSignal="pdout" hwResource="//@hwResources.13" required="false"/>
  <virtualSignals name="index_event_detection_out" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventdet_pdout_idx" hwSignal="pdout" hwResource="//@hwResources.14" required="false"/>
  <virtualSignals name="qclock_input" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu40_gp0unsync" hwSignal="gp0_unsync" hwResource="//@hwResources.5"/>
  <virtualSignals name="qdirection_input" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu40_gp1unsync" hwSignal="gp1_unsync" hwResource="//@hwResources.5"/>
  <virtualSignals name="timestamp_trigger_slice_st_input" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu40_gp2unsync" hwSignal="gp2_unsync" hwResource="//@hwResources.5"/>
  <virtualSignals name="position_counter_status_signal" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu40_st" hwSignal="st" hwResource="//@hwResources.5"/>
  <virtualSignals name="position_counter_status_input" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu41_gp0unsync" hwSignal="gp0_unsync" hwResource="//@hwResources.6" required="false"/>
  <virtualSignals name="revolution_counter_qdirection_input" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu41_gp1unsync" hwSignal="gp1_unsync" hwResource="//@hwResources.6" required="false"/>
  <virtualSignals name="timestamp_trigger_slice_st_input" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu41_gp2unsync" hwSignal="gp2_unsync" hwResource="//@hwResources.6" required="false"/>
  <virtualSignals name="pclock_input" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu42_gp0unsync" hwSignal="gp0_unsync" hwResource="//@hwResources.7"/>
  <virtualSignals name="timestamp_trigger_slice_st_input" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu42_gp1unsync" hwSignal="gp1_unsync" hwResource="//@hwResources.7"/>
  <virtualSignals name="syncstart_input" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu43_gp0unsync" hwSignal="gp0_unsync" hwResource="//@hwResources.8"/>
  <virtualSignals name="timestamp_trigger_slice_status_signal" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu43_st" hwSignal="st" hwResource="//@hwResources.8"/>
  <virtualSignals name="Phase A_signal" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/__pin_vs_encoder_posif_pad_ph_a" hwSignal="pin" hwResource="//@hwResources.16"/>
  <virtualSignals name="Phase B_signal" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/__pin_vs_encoder_posif_pad_ph_b" hwSignal="pin" hwResource="//@hwResources.17"/>
  <virtualSignals name="Index_signal" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/__pin_vs_encoder_posif_pad_idx" hwSignal="pin" hwResource="//@hwResources.18"/>
  <virtualSignals name="Encoder Enable Pad_signal" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/__pin_vs_encoder_posif_pad_enenc" hwSignal="pin" hwResource="//@hwResources.19"/>
  <requiredApps URI="http://resources/4.0.6/app/ENCODER_POSIF/0/appres_global_posif_0" requiredAppName="GLOBAL_POSIF" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../GLOBAL_POSIF/v4_0_18/GLOBAL_POSIF_0.app#/"/>
  </requiredApps>
  <requiredApps URI="http://resources/4.0.6/app/ENCODER_POSIF/0/appres_global_ccu4_0" requiredAppName="GLOBAL_CCU4" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../GLOBAL_CCU4/v4_1_14/GLOBAL_CCU4_0.app#/"/>
  </requiredApps>
  <requiredApps URI="http://resources/4.0.6/app/ENCODER_POSIF/0/appres_cpu_ctrl" requiredAppName="CPU_CTRL_XMC4" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.0.6/app/ENCODER_POSIF/0/appres_motorlibs" requiredAppName="MOTOR_LIB" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../MOTOR_LIB/v4_0_12/MOTOR_LIB_0.app#/"/>
  </requiredApps>
  <hwResources name="Phase A" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/hwres_port_pad_1" resourceGroupUri="port/p/*/pad/*" mResGrpUri="port/p/*/pad/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/Port1/Port1_1.dd#//@provided.11"/>
  </hwResources>
  <hwResources name="Phase B" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/hwres_port_pad_2" resourceGroupUri="port/p/*/pad/*" mResGrpUri="port/p/*/pad/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/Port1/Port1_1.dd#//@provided.6"/>
  </hwResources>
  <hwResources name="Index" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/hwres_port_pad_3" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Encoder Enable Pad" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/hwres_port_enable_encoder_pad" resourceGroupUri="port/p/*/pad/*" mResGrpUri="port/p/*/pad/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/Port5/Port5_5.dd#//@provided.6"/>
  </hwResources>
  <hwResources name="POSIF encoder" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/hwres_posif_hsc_qd_0" resourceGroupUri="peripheral/posif/*/posif/hsc_qd" mResGrpUri="peripheral/posif/*/posif/hsc_qd">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/POSIF0/POSIF0_0.dd#//@provided.0"/>
  </hwResources>
  <hwResources name="Position Count Slice" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/hwres_ccu4_slice0" resourceGroupUri="peripheral/ccu4/*/cc4/*" mResGrpUri="peripheral/ccu4/*/cc4/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/CCU40/CCU40_0.dd#//@provided.3"/>
  </hwResources>
  <hwResources name="Revolution Count Slice" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/hwres_ccu4_slice1" resourceGroupUri="" required="false" mResGrpUri="peripheral/ccu4/*/cc4/*"/>
  <hwResources name="Time Between Ticks Slice" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/hwres_ccu4_slice2" resourceGroupUri="peripheral/ccu4/*/cc4/*" mResGrpUri="peripheral/ccu4/*/cc4/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/CCU40/CCU40_0.dd#//@provided.16"/>
  </hwResources>
  <hwResources name="Time Stamp Trigger Slice" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/hwres_ccu4_slice3" resourceGroupUri="peripheral/ccu4/*/cc4/*" mResGrpUri="peripheral/ccu4/*/cc4/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/CCU40/CCU40_0.dd#//@provided.29"/>
  </hwResources>
  <hwResources name="ETL 1" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/hwres_ers_etl_1" resourceGroupUri="" required="false" mResGrpUri="peripheral/eru/*/ers_etl/*"/>
  <hwResources name="ETL 2" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/hwres_ers_etl_2" resourceGroupUri="" required="false" mResGrpUri="peripheral/eru/*/ers_etl/*"/>
  <hwResources name="ETL 3" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/hwres_ers_etl_3" resourceGroupUri="" required="false" mResGrpUri="peripheral/eru/*/ers_etl/*"/>
  <hwResources name="OGU 1" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/hwres_eru_ogu_1" resourceGroupUri="" required="false" mResGrpUri="peripheral/eru/*/ogu/*"/>
  <hwResources name="OGU 2" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/hwres_eru_ogu_2" resourceGroupUri="" required="false" mResGrpUri="peripheral/eru/*/ogu/*"/>
  <hwResources name="OGU 3" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/hwres_eru_ogu_3" resourceGroupUri="" required="false" mResGrpUri="peripheral/eru/*/ogu/*"/>
  <hwResources name="Time Stamp Trigger Period Match NVIC Node" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/hwres_nvic_trigslice_pm" resourceGroupUri="" required="false" mResGrpUri="peripheral/cpu/0/nvic/interrupt/*"/>
  <hwResources name="Phase A" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/__pin_hwres_port_pad_1" resourceGroupUri="devicepackage/0/*" mResGrpUri="devicepackage/0/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/DEVICEPACKAGE/DEVICEPACKAGE_0.dd#//@provided.14"/>
  </hwResources>
  <hwResources name="Phase B" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/__pin_hwres_port_pad_2" resourceGroupUri="devicepackage/0/*" mResGrpUri="devicepackage/0/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/DEVICEPACKAGE/DEVICEPACKAGE_0.dd#//@provided.13"/>
  </hwResources>
  <hwResources name="Index" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/__pin_hwres_port_pad_3" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Encoder Enable Pad" URI="http://resources/4.0.6/app/ENCODER_POSIF/0/__pin_hwres_port_enable_encoder_pad" resourceGroupUri="devicepackage/0/*" mResGrpUri="devicepackage/0/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/DEVICEPACKAGE/DEVICEPACKAGE_0.dd#//@provided.12"/>
  </hwResources>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu43_pmus_omds/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_triggen_pm_nvicsignal_in" systemDefined="true" sourceSignal="event_timestamp_trigger_period_match" targetSignal="sr_timestamp_trigger_periodmatch" required="false" srcVirtualSignal="//@virtualSignals.23" targetVirtualSignal="//@virtualSignals.22"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_global_ccu4_globalsignal/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_slice0_globalsignal" systemDefined="true" sourceSignal="ccu4_global" targetSignal="position_counter_slice_global_signal" targetVirtualSignal="//@virtualSignals.18" proxySrcVirtualSignalUri="http://resources/4.1.14/app/GLOBAL_CCU4/0/vs_global_ccu4_globalsignal" containingProxySignal="true">
    <downwardMapList xsi:type="ResourceModel:VirtualSignal" href="../../GLOBAL_CCU4/v4_1_14/GLOBAL_CCU4_0.app#//@virtualSignals.0"/>
    <srcVirtualSignal href="../../GLOBAL_CCU4/v4_1_14/GLOBAL_CCU4_0.app#//@virtualSignals.0"/>
  </connections>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_global_ccu4_globalsignal/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_slice1_globalsignal" systemDefined="true" sourceSignal="ccu4_global" targetSignal="revolution_counter_slice_global_signal" required="false" targetVirtualSignal="//@virtualSignals.19" proxySrcVirtualSignalUri="http://resources/4.1.14/app/GLOBAL_CCU4/0/vs_global_ccu4_globalsignal" containingProxySignal="true">
    <srcVirtualSignal href="../../GLOBAL_CCU4/v4_1_14/GLOBAL_CCU4_0.app#//@virtualSignals.0"/>
  </connections>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_global_ccu4_globalsignal/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_slice2_globalsignal" systemDefined="true" sourceSignal="ccu4_global" targetSignal="time_capture_slice_global_signal" targetVirtualSignal="//@virtualSignals.20" proxySrcVirtualSignalUri="http://resources/4.1.14/app/GLOBAL_CCU4/0/vs_global_ccu4_globalsignal" containingProxySignal="true">
    <downwardMapList xsi:type="ResourceModel:VirtualSignal" href="../../GLOBAL_CCU4/v4_1_14/GLOBAL_CCU4_0.app#//@virtualSignals.0"/>
    <srcVirtualSignal href="../../GLOBAL_CCU4/v4_1_14/GLOBAL_CCU4_0.app#//@virtualSignals.0"/>
  </connections>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_global_ccu4_globalsignal/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_slice3_globalsignal" systemDefined="true" sourceSignal="ccu4_global" targetSignal="timestamp_triggerslice_global_signal" targetVirtualSignal="//@virtualSignals.21" proxySrcVirtualSignalUri="http://resources/4.1.14/app/GLOBAL_CCU4/0/vs_global_ccu4_globalsignal" containingProxySignal="true">
    <downwardMapList xsi:type="ResourceModel:VirtualSignal" href="../../GLOBAL_CCU4/v4_1_14/GLOBAL_CCU4_0.app#//@virtualSignals.0"/>
    <srcVirtualSignal href="../../GLOBAL_CCU4/v4_1_14/GLOBAL_CCU4_0.app#//@virtualSignals.0"/>
  </connections>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_out0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu40_gp0unsync" systemDefined="true" sourceSignal="quadrature_clock" targetSignal="qclock_input" srcVirtualSignal="//@virtualSignals.8" targetVirtualSignal="//@virtualSignals.37"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_out1/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu40_gp1unsync" systemDefined="true" sourceSignal="quadrature_direction" targetSignal="qdirection_input" srcVirtualSignal="//@virtualSignals.9" targetVirtualSignal="//@virtualSignals.38"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu43_st/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu40_gp2unsync" systemDefined="true" sourceSignal="timestamp_trigger_slice_status_signal" targetSignal="timestamp_trigger_slice_st_input" srcVirtualSignal="//@virtualSignals.47" targetVirtualSignal="//@virtualSignals.39"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu40_st/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu41_gp0unsync" systemDefined="true" sourceSignal="position_counter_status_signal" targetSignal="position_counter_status_input" required="false" srcVirtualSignal="//@virtualSignals.40" targetVirtualSignal="//@virtualSignals.41"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_out1/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu41_gp1unsync" systemDefined="true" sourceSignal="quadrature_direction" targetSignal="revolution_counter_qdirection_input" required="false" srcVirtualSignal="//@virtualSignals.9" targetVirtualSignal="//@virtualSignals.42"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu43_st/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu41_gp2unsync" systemDefined="true" sourceSignal="timestamp_trigger_slice_status_signal" targetSignal="timestamp_trigger_slice_st_input" required="false" srcVirtualSignal="//@virtualSignals.47" targetVirtualSignal="//@virtualSignals.43"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_out2/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu42_gp0unsync" systemDefined="true" sourceSignal="period_clock" targetSignal="pclock_input" srcVirtualSignal="//@virtualSignals.10" targetVirtualSignal="//@virtualSignals.44"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu43_st/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu42_gp1unsync" systemDefined="true" sourceSignal="timestamp_trigger_slice_status_signal" targetSignal="timestamp_trigger_slice_st_input" srcVirtualSignal="//@virtualSignals.47" targetVirtualSignal="//@virtualSignals.45"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_ph_a/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_input0" systemDefined="true" sourceSignal="phase_a_pad" targetSignal="phase_a" srcVirtualSignal="//@virtualSignals.14" targetVirtualSignal="//@virtualSignals.0"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_ph_b/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_input1" systemDefined="true" sourceSignal="phase_b_pad" targetSignal="phase_b" srcVirtualSignal="//@virtualSignals.15" targetVirtualSignal="//@virtualSignals.1"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_idx/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_input2" systemDefined="true" sourceSignal="index_pad" targetSignal="index" required="false" srcVirtualSignal="//@virtualSignals.16" targetVirtualSignal="//@virtualSignals.2"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_ph_a/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventgen_input_a_ph_a" systemDefined="true" sourceSignal="phase_a_pad" targetSignal="phase_a_event_generation_signal_a" required="false" srcVirtualSignal="//@virtualSignals.14" targetVirtualSignal="//@virtualSignals.25"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_ph_b/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventgen_input_a_ph_b" systemDefined="true" sourceSignal="phase_b_pad" targetSignal="phase_b_event_generation_signal_a" required="false" srcVirtualSignal="//@virtualSignals.15" targetVirtualSignal="//@virtualSignals.26"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_idx/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventgen_input_a_idx" systemDefined="true" sourceSignal="index_pad" targetSignal="index_event_generation_signal_a" required="false" srcVirtualSignal="//@virtualSignals.16" targetVirtualSignal="//@virtualSignals.27"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventgen_flagstatus_ph_a/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventdet_pdin_ph_a" systemDefined="true" sourceSignal="phase_a_event_generation_flag_status" targetSignal="phase_a_event_detection_in" required="false" srcVirtualSignal="//@virtualSignals.28" targetVirtualSignal="//@virtualSignals.31"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventgen_flagstatus_ph_b/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventdet_pdin_ph_b" systemDefined="true" sourceSignal="phase_b_event_generation_flag_status" targetSignal="phase_b_event_detection_in" required="false" srcVirtualSignal="//@virtualSignals.29" targetVirtualSignal="//@virtualSignals.32"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventgen_flagstatus_idx/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventdet_pdin_idx" systemDefined="true" sourceSignal="index_event_generation_flag_status" targetSignal="index_event_detection_in" required="false" srcVirtualSignal="//@virtualSignals.30" targetVirtualSignal="//@virtualSignals.33"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventdet_pdout_ph_a/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_input0" systemDefined="true" sourceSignal="phase_a_event_detection_out" targetSignal="phase_a" required="false" srcVirtualSignal="//@virtualSignals.34" targetVirtualSignal="//@virtualSignals.0"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventdet_pdout_ph_b/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_input1" systemDefined="true" sourceSignal="phase_b_event_detection_out" targetSignal="phase_b" required="false" srcVirtualSignal="//@virtualSignals.35" targetVirtualSignal="//@virtualSignals.1"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_eventdet_pdout_idx/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_input2" systemDefined="true" sourceSignal="index_event_detection_out" targetSignal="index" required="false" srcVirtualSignal="//@virtualSignals.36" targetVirtualSignal="//@virtualSignals.2"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_out5/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_ccu43_gp0unsync" systemDefined="true" sourceSignal="syncstart" targetSignal="syncstart_input" srcVirtualSignal="//@virtualSignals.13" targetVirtualSignal="//@virtualSignals.46"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_ph_a/http://resources/4.0.6/app/ENCODER_POSIF/0/__pin_vs_encoder_posif_pad_ph_a" systemDefined="true" sourceSignal="phase_a_pad" targetSignal="Phase A_signal" srcVirtualSignal="//@virtualSignals.14" targetVirtualSignal="//@virtualSignals.48"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/__pin_vs_encoder_posif_pad_ph_a/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_ph_a" systemDefined="true" sourceSignal="Phase A_signal" targetSignal="phase_a_pad" srcVirtualSignal="//@virtualSignals.48" targetVirtualSignal="//@virtualSignals.14"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_ph_b/http://resources/4.0.6/app/ENCODER_POSIF/0/__pin_vs_encoder_posif_pad_ph_b" systemDefined="true" sourceSignal="phase_b_pad" targetSignal="Phase B_signal" srcVirtualSignal="//@virtualSignals.15" targetVirtualSignal="//@virtualSignals.49"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/__pin_vs_encoder_posif_pad_ph_b/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_ph_b" systemDefined="true" sourceSignal="Phase B_signal" targetSignal="phase_b_pad" srcVirtualSignal="//@virtualSignals.49" targetVirtualSignal="//@virtualSignals.15"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_idx/http://resources/4.0.6/app/ENCODER_POSIF/0/__pin_vs_encoder_posif_pad_idx" systemDefined="true" sourceSignal="index_pad" targetSignal="Index_signal" srcVirtualSignal="//@virtualSignals.16" targetVirtualSignal="//@virtualSignals.50"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/__pin_vs_encoder_posif_pad_idx/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_idx" systemDefined="true" sourceSignal="Index_signal" targetSignal="index_pad" srcVirtualSignal="//@virtualSignals.50" targetVirtualSignal="//@virtualSignals.16"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_enenc/http://resources/4.0.6/app/ENCODER_POSIF/0/__pin_vs_encoder_posif_pad_enenc" systemDefined="true" sourceSignal="encoder_enable_pad" targetSignal="Encoder Enable Pad_signal" srcVirtualSignal="//@virtualSignals.17" targetVirtualSignal="//@virtualSignals.51"/>
  <connections URI="http://resources/4.0.6/app/ENCODER_POSIF/0/http://resources/4.0.6/app/ENCODER_POSIF/0/__pin_vs_encoder_posif_pad_enenc/http://resources/4.0.6/app/ENCODER_POSIF/0/vs_encoder_posif_pad_enenc" systemDefined="true" sourceSignal="Encoder Enable Pad_signal" targetSignal="encoder_enable_pad" srcVirtualSignal="//@virtualSignals.51" targetVirtualSignal="//@virtualSignals.17"/>
</ResourceModel:App>
