-- VHDL Entity sbus_awfg_lib.uart_tx.symbol
--
-- Created:
--          by - Net.UNKNOWN (M00443)
--          at - 16:23:58 17.07.2006
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity uart_tx is
   generic( 
      baudrate_g      : integer := 9600;
      core_clk_freq_g : integer := 50000000
   );
   port( 
      clk    : in     std_logic;                      -- core clock
      din    : in     std_logic_vector (7 downto 0);  -- parallel tx data input
      reset  : in     std_logic;                      -- synchronous, active high reset
      we     : in     std_logic;                      -- data write enable
      tx_ack : out    std_logic;                      -- transmit acknowledge
      txd    : out    std_logic                       -- serial  transmit data
   );

-- Declarations

end uart_tx ;

--
-- VHDL Architecture sbus_awfg_lib.uart_tx.fsm
--
-- Created:
--          by - Net.UNKNOWN (M00443)
--          at - 14:47:46 28.11.2008
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;
 
architecture fsm of uart_tx is

   -- Architecture Declarations
   -- reload value for the baudrate timer --------------------------------------------------
   constant bdcnt_mod_c: integer :=  core_clk_freq_g / baudrate_g;
   
   signal bdcnt_en: std_logic;
   signal bdcnt_tc: std_logic;
   signal bdcnt: integer range 0 to bdcnt_mod_c-1;
   signal tx_reg: std_logic_vector(din'left+2 downto 0);
   signal bit_cnt: integer range 0 to din'length+1;

   type state_type is (
      s_wait,
      s_tx
   );
 
   -- State vector declaration
   attribute state_vector : string;
   attribute state_vector of fsm : architecture is "current_state";

   -- Declare current and next state signals
   signal current_state : state_type;
   signal next_state : state_type;

   -- Declare any pre-registered internal signals
   signal tx_ack_cld : std_logic ;-- transmit acknowledge

begin

   -----------------------------------------------------------------
   clocked_proc : process ( 
      clk
   )
   -----------------------------------------------------------------
   begin
      if (clk'event and clk = '1') then
         if (reset = '1') then
            current_state <= s_wait;
            -- Default Reset Values
            tx_ack_cld <= '0';
            tx_reg <= (others => '1');
         else
            current_state <= next_state;
            -- Default Assignment To Internals
            tx_ack_cld <= '0';

            -- Combined Actions
            case current_state is
               when s_wait => 
                  if (we = '1') then 
                     tx_reg <= '1' & din & '0';
                     bit_cnt <= din'length+1;
                  end if;
               when s_tx => 
                  if (bdcnt_tc = '1' and bit_cnt = 0) then 
                     tx_ack_cld <= '1';
                  elsif (bdcnt_tc = '1') then 
                     tx_reg <= '1' & tx_reg(tx_reg'left downto 1);
                     bit_cnt <= bit_cnt -1;
                  end if;
               when others =>
                  null;
            end case;
         end if;
      end if;
   end process clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : process ( 
      bdcnt_tc,
      bit_cnt,
      current_state,
      we
   )
   -----------------------------------------------------------------
   begin
      case current_state is
         when s_wait => 
            if (we = '1') then 
               next_state <= s_tx;
            else
               next_state <= s_wait;
            end if;
         when s_tx => 
            if (bdcnt_tc = '1' and bit_cnt = 0) then 
               next_state <= s_wait;
            elsif (bdcnt_tc = '1') then 
               next_state <= s_tx;
            else
               next_state <= s_tx;
            end if;
         when others =>
            next_state <= s_wait;
      end case;
   end process nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : process ( 
      current_state
   )
   -----------------------------------------------------------------
   begin
      -- Default Assignment To Internals
      bdcnt_en <= '0';

      -- Combined Actions
      case current_state is
         when s_tx => 
            bdcnt_en <= '1';
         when others =>
            null;
      end case;
   end process output_proc;
 
   -- Concurrent Statements
   -- Clocked output assignments
   tx_ack <= tx_ack_cld;
   -- baudrate counter ----------
   process(clk)
   begin
      if clk='1' and clk'event then
         if bdcnt_en = '0'  then
             bdcnt <= 0;
         else
             if bdcnt_tc = '1' then
                 bdcnt <= 0;
             else
               bdcnt <= bdcnt + 1;
             end if;
         end if;
     end if;
   end process;
   
   bdcnt_tc <= '1' when bdcnt = bdcnt_mod_c - 1 else '0';
   
   txd <= tx_reg(0);
end fsm;
