#--Onboard Buttons,Sliders,LEDs -------------------------------
set_property PACKAGE_PIN Y16 [get_ports {buttons[3]}]
set_property PACKAGE_PIN V16 [get_ports {buttons[2]}]
set_property PACKAGE_PIN P16 [get_ports {buttons[1]}]
set_property PACKAGE_PIN R18 [get_ports {buttons[0]}]
set_property PACKAGE_PIN T16 [get_ports {sliders[3]}]
set_property PACKAGE_PIN W13 [get_ports {sliders[2]}]
set_property PACKAGE_PIN P15 [get_ports {sliders[1]}]
set_property PACKAGE_PIN G15 [get_ports {sliders[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sliders[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sliders[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sliders[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sliders[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports dac_dual_dac_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports dac_dual_dac_sdin0]
set_property IOSTANDARD LVCMOS33 [get_ports dac_dual_dac_sdin1]
set_property IOSTANDARD LVCMOS33 [get_ports dac_dual_dac_sync]
set_property PACKAGE_PIN T20 [get_ports dac_dual_dac_sdin0]
set_property PACKAGE_PIN U20 [get_ports dac_dual_dac_sclk]
set_property PACKAGE_PIN V20 [get_ports dac_dual_dac_sync]
set_property PACKAGE_PIN Y18 [get_ports dac_dual_dac_sdin1]
set_property PACKAGE_PIN D18 [get_ports {leds[3]}]
set_property PACKAGE_PIN G14 [get_ports {leds[2]}]
set_property PACKAGE_PIN M15 [get_ports {leds[1]}]
set_property PACKAGE_PIN M14 [get_ports {leds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]

#Pmod JC ----------------------------------------------
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_jc[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_jc[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_jc[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_jc[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_jc[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_jc[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_jc[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_jc[0]}]
set_property PACKAGE_PIN V15 [get_ports {pmod_jc[0]}]
set_property PACKAGE_PIN W15 [get_ports {pmod_jc[1]}]
set_property PACKAGE_PIN T11 [get_ports {pmod_jc[2]}]
set_property PACKAGE_PIN T10 [get_ports {pmod_jc[3]}]
set_property PACKAGE_PIN W14 [get_ports {pmod_jc[4]}]
set_property PACKAGE_PIN Y14 [get_ports {pmod_jc[5]}]
set_property PACKAGE_PIN T12 [get_ports {pmod_jc[6]}]
set_property PACKAGE_PIN U12 [get_ports {pmod_jc[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
set_property PACKAGE_PIN L14 [get_ports uart_txd]
set_property PACKAGE_PIN K16 [get_ports uart_rxd]



