-- VHDL Entity sbus_uart_lib.tb_top_uart.symbol
--
-- Created:
--          by - net.UNKNOWN (KPERSM7467)
--          at - 11:01:08 08.11.2018
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.2 (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity tb_top_uart is
-- Declarations

end tb_top_uart ;

--
-- VHDL Architecture sbus_uart_lib.tb_top_uart.struct
--
-- Created:
--          by - net.UNKNOWN (KPERSM7467)
--          at - 11:15:04 09.11.2018
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.2 (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

library sbus_uart_lib;

architecture struct of tb_top_uart is

   -- Architecture declarations

   -- Internal signal declarations
   signal clk        : std_logic;
   signal reset      : std_logic;
   signal rx_data    : std_logic_vector(7 downto 0);
   signal rx_data_en : std_logic;
   signal rxd        : std_logic := '1';
   signal tx_data    : std_logic_vector(7 downto 0);
   signal tx_trig    : std_logic;
   signal txd        : std_logic := '1';


   -- Component Declarations
   component bhv_clock_gen
   generic (
      clk_period_g      : time    := 20 ns;
      reset_cycles_g    : integer := 10;
      enable_a_cycles_g : integer := 1;
      enable_b_cycles_g : integer := 1
   );
   port (
      clk      : out    std_logic;
      enable_a : out    std_logic;
      enable_b : out    std_logic;
      reset    : out    std_logic
   );
   end component;
   component bhv_strobe_gen
   generic (
      timestamp_g  : time    := 1 us;
      period_g     : time    := 00us;
      singleshot_g : boolean := true
   );
   port (
      clk : in     std_logic;
      stb : out    std_logic
   );
   end component;
   component top_uart
   generic (
      tx_baudrate_g : integer := 115200;
      rx_baudrate_g : integer := 115200
   );
   port (
      clk        : in     std_logic ;
      reset      : in     std_logic ;
      rxd        : in     std_logic ;
      tx_data    : in     std_logic_vector (7 downto 0);
      tx_trig    : in     std_logic ;
      rx_data    : out    std_logic_vector (7 downto 0);
      rx_data_en : out    std_logic ;
      txd        : out    std_logic 
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : bhv_clock_gen use entity sbus_uart_lib.bhv_clock_gen;
   for all : bhv_strobe_gen use entity sbus_uart_lib.bhv_strobe_gen;
   for all : top_uart use entity sbus_uart_lib.top_uart;
   -- pragma synthesis_on


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 tx_databyte
   tx_data <= X"53";                             

   -- HDL Embedded Text Block 2 transport_delay
   --delay the transmitted signal by arbitrary delay time
   rxd <= transport txd after 49.2 us;                                   


   -- Instance port mappings.
   U_0 : bhv_clock_gen
      generic map (
         clk_period_g      => 8 ns,
         reset_cycles_g    => 10,
         enable_a_cycles_g => 1,
         enable_b_cycles_g => 1
      )
      port map (
         clk      => clk,
         enable_a => open,
         enable_b => open,
         reset    => reset
      );
   U_2 : bhv_strobe_gen
      generic map (
         timestamp_g  => 5.2 us,
         period_g     => 202us,
         singleshot_g => false
      )
      port map (
         clk => clk,
         stb => tx_trig
      );
   U_1 : top_uart
      generic map (
         tx_baudrate_g => 112200,
         rx_baudrate_g => 115200
      )
      port map (
         clk        => clk,
         reset      => reset,
         rxd        => rxd,
         tx_data    => tx_data,
         tx_trig    => tx_trig,
         rx_data    => rx_data,
         rx_data_en => rx_data_en,
         txd        => txd
      );

end struct;
