# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zybo_client_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1134, 632)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -141, 1097, 880))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setMinimumSize(QtCore.QSize(1000, 50))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_datetime = QtWidgets.QLabel(self.groupBox)
        self.label_datetime.setGeometry(QtCore.QRect(605, 15, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_datetime.setFont(font)
        self.label_datetime.setObjectName("label_datetime")
        self.pushButton_ConnectToServer = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_ConnectToServer.setGeometry(QtCore.QRect(10, 10, 111, 23))
        self.pushButton_ConnectToServer.setObjectName("pushButton_ConnectToServer")
        self.pushButton_CloseServer = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_CloseServer.setGeometry(QtCore.QRect(800, 15, 106, 23))
        self.pushButton_CloseServer.setObjectName("pushButton_CloseServer")
        self.pushButton_PollSignals = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_PollSignals.setGeometry(QtCore.QRect(145, 10, 106, 23))
        self.pushButton_PollSignals.setObjectName("pushButton_PollSignals")
        self.spinBox_PollInterval = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_PollInterval.setGeometry(QtCore.QRect(275, 10, 51, 22))
        self.spinBox_PollInterval.setMaximum(10000)
        self.spinBox_PollInterval.setProperty("value", 200)
        self.spinBox_PollInterval.setObjectName("spinBox_PollInterval")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(335, 15, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_cpu_usage = QtWidgets.QLabel(self.groupBox)
        self.label_cpu_usage.setGeometry(QtCore.QRect(455, 15, 106, 16))
        self.label_cpu_usage.setObjectName("label_cpu_usage")
        self.label_logo_fh = QtWidgets.QLabel(self.groupBox)
        self.label_logo_fh.setGeometry(QtCore.QRect(935, 5, 167, 42))
        self.label_logo_fh.setObjectName("label_logo_fh")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 800))
        self.tabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_2.setGeometry(QtCore.QRect(-10, 5, 891, 561))
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.comboBox_SelectedProject = QtWidgets.QComboBox(self.tab_10)
        self.comboBox_SelectedProject.setGeometry(QtCore.QRect(140, 40, 181, 22))
        self.comboBox_SelectedProject.setEditable(True)
        self.comboBox_SelectedProject.setObjectName("comboBox_SelectedProject")
        self.label_2 = QtWidgets.QLabel(self.tab_10)
        self.label_2.setGeometry(QtCore.QRect(40, 45, 96, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_NewProject = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_NewProject.setGeometry(QtCore.QRect(675, 40, 171, 20))
        self.lineEdit_NewProject.setObjectName("lineEdit_NewProject")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_4.setGeometry(QtCore.QRect(580, 40, 81, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tableWidget_ProjectSettings = QtWidgets.QTableWidget(self.tab_10)
        self.tableWidget_ProjectSettings.setGeometry(QtCore.QRect(30, 95, 836, 200))
        self.tableWidget_ProjectSettings.setMinimumSize(QtCore.QSize(0, 200))
        self.tableWidget_ProjectSettings.setAcceptDrops(True)
        self.tableWidget_ProjectSettings.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_ProjectSettings.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_ProjectSettings.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_ProjectSettings.setDragEnabled(True)
        self.tableWidget_ProjectSettings.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget_ProjectSettings.setAlternatingRowColors(True)
        self.tableWidget_ProjectSettings.setRowCount(6)
        self.tableWidget_ProjectSettings.setColumnCount(3)
        self.tableWidget_ProjectSettings.setObjectName("tableWidget_ProjectSettings")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ProjectSettings.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ProjectSettings.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ProjectSettings.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ProjectSettings.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ProjectSettings.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ProjectSettings.setItem(5, 0, item)
        self.tableWidget_ProjectSettings.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_ProjectSettings.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_ProjectSettings.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_ProjectSettings.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget_ProjectSettings.verticalHeader().setMinimumSectionSize(18)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_5.setGeometry(QtCore.QRect(715, 505, 146, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tableWidget_IpCores = QtWidgets.QTableWidget(self.tab_10)
        self.tableWidget_IpCores.setGeometry(QtCore.QRect(30, 315, 836, 151))
        self.tableWidget_IpCores.setMinimumSize(QtCore.QSize(0, 150))
        self.tableWidget_IpCores.setDragEnabled(True)
        self.tableWidget_IpCores.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget_IpCores.setAlternatingRowColors(True)
        self.tableWidget_IpCores.setRowCount(6)
        self.tableWidget_IpCores.setColumnCount(6)
        self.tableWidget_IpCores.setObjectName("tableWidget_IpCores")
        self.tableWidget_IpCores.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget_IpCores.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_IpCores.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_IpCores.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget_IpCores.verticalHeader().setMinimumSectionSize(18)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_8.setGeometry(QtCore.QRect(530, 505, 156, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton = QtWidgets.QPushButton(self.tab_10)
        self.pushButton.setGeometry(QtCore.QRect(35, 505, 121, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_PmodConn_1 = QtWidgets.QLabel(self.tab_6)
        self.label_PmodConn_1.setGeometry(QtCore.QRect(600, 100, 206, 76))
        self.label_PmodConn_1.setObjectName("label_PmodConn_1")
        self.tableWidget_Board_Zybo = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_Board_Zybo.setGeometry(QtCore.QRect(10, 25, 531, 200))
        self.tableWidget_Board_Zybo.setMinimumSize(QtCore.QSize(0, 200))
        self.tableWidget_Board_Zybo.setDragEnabled(True)
        self.tableWidget_Board_Zybo.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget_Board_Zybo.setRowCount(8)
        self.tableWidget_Board_Zybo.setColumnCount(5)
        self.tableWidget_Board_Zybo.setObjectName("tableWidget_Board_Zybo")
        self.tableWidget_Board_Zybo.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_Board_Zybo.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget_Board_Zybo.verticalHeader().setMinimumSectionSize(18)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tableWidget_Board_Zybo_z7_10 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_Board_Zybo_z7_10.setGeometry(QtCore.QRect(10, 25, 531, 200))
        self.tableWidget_Board_Zybo_z7_10.setMinimumSize(QtCore.QSize(0, 200))
        self.tableWidget_Board_Zybo_z7_10.setDragEnabled(True)
        self.tableWidget_Board_Zybo_z7_10.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget_Board_Zybo_z7_10.setRowCount(8)
        self.tableWidget_Board_Zybo_z7_10.setColumnCount(5)
        self.tableWidget_Board_Zybo_z7_10.setObjectName("tableWidget_Board_Zybo_z7_10")
        self.tableWidget_Board_Zybo_z7_10.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_Board_Zybo_z7_10.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget_Board_Zybo_z7_10.verticalHeader().setMinimumSectionSize(18)
        self.label_PmodConn_2 = QtWidgets.QLabel(self.tab_7)
        self.label_PmodConn_2.setGeometry(QtCore.QRect(600, 100, 201, 71))
        self.label_PmodConn_2.setObjectName("label_PmodConn_2")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tableWidget_Board_Zybo_z7_20 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_Board_Zybo_z7_20.setGeometry(QtCore.QRect(10, 25, 531, 200))
        self.tableWidget_Board_Zybo_z7_20.setMinimumSize(QtCore.QSize(0, 200))
        self.tableWidget_Board_Zybo_z7_20.setDragEnabled(True)
        self.tableWidget_Board_Zybo_z7_20.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget_Board_Zybo_z7_20.setRowCount(8)
        self.tableWidget_Board_Zybo_z7_20.setColumnCount(5)
        self.tableWidget_Board_Zybo_z7_20.setObjectName("tableWidget_Board_Zybo_z7_20")
        self.tableWidget_Board_Zybo_z7_20.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_Board_Zybo_z7_20.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget_Board_Zybo_z7_20.verticalHeader().setMinimumSectionSize(18)
        self.label_PmodConn_3 = QtWidgets.QLabel(self.tab_8)
        self.label_PmodConn_3.setGeometry(QtCore.QRect(600, 100, 206, 86))
        self.label_PmodConn_3.setObjectName("label_PmodConn_3")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.label_logo_board = QtWidgets.QLabel(self.tab_4)
        self.label_logo_board.setGeometry(QtCore.QRect(890, 5, 200, 155))
        self.label_logo_board.setObjectName("label_logo_board")
        self.label_logo_vivado = QtWidgets.QLabel(self.tab_4)
        self.label_logo_vivado.setGeometry(QtCore.QRect(890, 160, 200, 128))
        self.label_logo_vivado.setObjectName("label_logo_vivado")
        self.label_logo_fpgawiz = QtWidgets.QLabel(self.tab_4)
        self.label_logo_fpgawiz.setGeometry(QtCore.QRect(915, 315, 150, 155))
        self.label_logo_fpgawiz.setObjectName("label_logo_fpgawiz")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_Signals0 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_Signals0.setGeometry(QtCore.QRect(235, 35, 801, 726))
        self.tableWidget_Signals0.setMinimumSize(QtCore.QSize(0, 500))
        self.tableWidget_Signals0.setDragEnabled(True)
        self.tableWidget_Signals0.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget_Signals0.setAlternatingRowColors(True)
        self.tableWidget_Signals0.setRowCount(100)
        self.tableWidget_Signals0.setColumnCount(5)
        self.tableWidget_Signals0.setObjectName("tableWidget_Signals0")
        self.tableWidget_Signals0.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_Signals0.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_Signals0.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget_Signals0.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_Signals0.verticalHeader().setStretchLastSection(False)
        self.comboBox_GetSignals0 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_GetSignals0.setGeometry(QtCore.QRect(895, 5, 141, 22))
        self.comboBox_GetSignals0.setObjectName("comboBox_GetSignals0")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(235, 5, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 5, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.spinBox_GetRegister0 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_GetRegister0.setGeometry(QtCore.QRect(80, 5, 42, 22))
        self.spinBox_GetRegister0.setMaximum(32)
        self.spinBox_GetRegister0.setProperty("value", 32)
        self.spinBox_GetRegister0.setObjectName("spinBox_GetRegister0")
        self.tableWidget_Register0 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_Register0.setGeometry(QtCore.QRect(0, 35, 231, 726))
        self.tableWidget_Register0.setAlternatingRowColors(True)
        self.tableWidget_Register0.setRowCount(32)
        self.tableWidget_Register0.setColumnCount(2)
        self.tableWidget_Register0.setObjectName("tableWidget_Register0")
        self.tableWidget_Register0.verticalHeader().setDefaultSectionSize(20)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(815, 10, 76, 13))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.label_logo = QtWidgets.QLabel(self.tab_11)
        self.label_logo.setGeometry(QtCore.QRect(940, 10, 150, 156))
        self.label_logo.setObjectName("label_logo")
        self.groupBox_Dashboard = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_Dashboard.setGeometry(QtCore.QRect(130, 5, 800, 536))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Dashboard.sizePolicy().hasHeightForWidth())
        self.groupBox_Dashboard.setSizePolicy(sizePolicy)
        self.groupBox_Dashboard.setObjectName("groupBox_Dashboard")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_2.setGeometry(QtCore.QRect(5, 15, 111, 531))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 115, 91, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 40, 91, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 70, 91, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 270, 91, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_15.setGeometry(QtCore.QRect(10, 350, 91, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_20.setGeometry(QtCore.QRect(10, 140, 91, 23))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_17.setGeometry(QtCore.QRect(10, 165, 91, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_21.setGeometry(QtCore.QRect(10, 205, 91, 23))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_16.setGeometry(QtCore.QRect(10, 230, 91, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_RemoveWidget = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_RemoveWidget.setGeometry(QtCore.QRect(20, 385, 75, 23))
        self.pushButton_RemoveWidget.setObjectName("pushButton_RemoveWidget")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_12.setGeometry(QtCore.QRect(20, 410, 75, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 435, 75, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_19.setGeometry(QtCore.QRect(20, 500, 75, 23))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_18.setGeometry(QtCore.QRect(20, 475, 75, 23))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_22.setGeometry(QtCore.QRect(10, 295, 91, 23))
        self.pushButton_22.setObjectName("pushButton_22")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_application = QtWidgets.QWidget()
        self.tab_application.setObjectName("tab_application")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_application)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_application = QtWidgets.QScrollArea(self.tab_application)
        self.scrollArea_application.setWidgetResizable(True)
        self.scrollArea_application.setObjectName("scrollArea_application")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_application.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_application)
        self.tabWidget.addTab(self.tab_application, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1134, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuProject = QtWidgets.QMenu(self.menuFile)
        self.menuProject.setObjectName("menuProject")
        self.menuBoard = QtWidgets.QMenu(self.menubar)
        self.menuBoard.setObjectName("menuBoard")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCreate = QtWidgets.QAction(MainWindow)
        self.actionCreate.setObjectName("actionCreate")
        self.actionConnect_Main_Server = QtWidgets.QAction(MainWindow)
        self.actionConnect_Main_Server.setObjectName("actionConnect_Main_Server")
        self.actionConnect_Aux_Server = QtWidgets.QAction(MainWindow)
        self.actionConnect_Aux_Server.setObjectName("actionConnect_Aux_Server")
        self.actionStart_APU = QtWidgets.QAction(MainWindow)
        self.actionStart_APU.setObjectName("actionStart_APU")
        self.actionStop_APU = QtWidgets.QAction(MainWindow)
        self.actionStop_APU.setObjectName("actionStop_APU")
        self.menuProject.addAction(self.actionCreate)
        self.menuFile.addAction(self.menuProject.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuBoard.addAction(self.actionConnect_Main_Server)
        self.menuBoard.addAction(self.actionConnect_Aux_Server)
        self.menuBoard.addSeparator()
        self.menuBoard.addAction(self.actionStart_APU)
        self.menuBoard.addAction(self.actionStop_APU)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBoard.menuAction())
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        self.pushButton_ConnectToServer.clicked.connect(MainWindow.onCmd_ConnectToServer)
        self.pushButton_CloseServer.clicked.connect(MainWindow.onCmd_CloseServer)
        self.pushButton_PollSignals.clicked.connect(MainWindow.onCmd_PollSignals)
        self.pushButton_4.clicked.connect(MainWindow.onCmd_NewProject)
        self.pushButton_7.clicked.connect(MainWindow.onCmd_ListSignals)
        self.pushButton_5.clicked.connect(MainWindow.onCmd_UpdateProject)
        self.pushButton_8.clicked.connect(MainWindow.onCmd_SyncIpToBoard)
        self.comboBox_SelectedProject.currentIndexChanged['int'].connect(MainWindow.onCmd_SelectedProject)
        self.pushButton_2.clicked.connect(MainWindow.onCmd_GetRegisterN)
        self.comboBox_GetSignals0.currentIndexChanged['QString'].connect(MainWindow.onCmd_CurrentIpChanged)
        self.pushButton_9.clicked.connect(MainWindow.onCmd_AddLedToDashboard)
        self.pushButton_10.clicked.connect(MainWindow.onCmd_AddDisplayToDashboard)
        self.pushButton_11.clicked.connect(MainWindow.onCmd_Test)
        self.pushButton_12.clicked.connect(MainWindow.onCmd_LoadDashboard)
        self.pushButton_RemoveWidget.clicked.connect(MainWindow.onCmd_RemoveFromDashboard)
        self.pushButton_13.clicked.connect(MainWindow.onCmd_AddCheckboxToDashboard)
        self.pushButton_14.clicked.connect(MainWindow.onCmd_AddLabelToDashboard)
        self.pushButton_15.clicked.connect(MainWindow.onCmd_AddPushbuttonToDashboard)
        self.pushButton_16.clicked.connect(MainWindow.onCmd_AddSliderToDashboard)
        self.pushButton_17.clicked.connect(MainWindow.onCmd_AddDialToDashboard)
        self.pushButton_18.clicked.connect(MainWindow.onCmd_ApplySignalSetting)
        self.pushButton_19.clicked.connect(MainWindow.onCmd_PrintSignals)
        self.pushButton_20.clicked.connect(MainWindow.onCmd_AddSpinboxToDashboard)
        self.pushButton_21.clicked.connect(MainWindow.onCmd_AddLSliderToDashboard)
        self.pushButton_22.clicked.connect(MainWindow.onCmd_AddLineEditToDashboard)
        self.pushButton.clicked.connect(MainWindow.onCmd_UpdateBitstream)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_datetime.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_ConnectToServer.setText(_translate("MainWindow", "CONNECT to Server"))
        self.pushButton_CloseServer.setText(_translate("MainWindow", "SHUTDOWN Server"))
        self.pushButton_PollSignals.setText(_translate("MainWindow", "POLL Signals"))
        self.label_3.setText(_translate("MainWindow", "Update Interval / ms"))
        self.label_cpu_usage.setText(_translate("MainWindow", "TextLabel"))
        self.label_logo_fh.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Available Projects"))
        self.pushButton_4.setText(_translate("MainWindow", "NEW Project"))
        self.tableWidget_ProjectSettings.setSortingEnabled(True)
        __sortingEnabled = self.tableWidget_ProjectSettings.isSortingEnabled()
        self.tableWidget_ProjectSettings.setSortingEnabled(False)
        item = self.tableWidget_ProjectSettings.item(0, 0)
        item.setText(_translate("MainWindow", "prj_name"))
        item = self.tableWidget_ProjectSettings.item(1, 0)
        item.setText(_translate("MainWindow", "prj_path"))
        item = self.tableWidget_ProjectSettings.item(2, 0)
        item.setText(_translate("MainWindow", "impl_path"))
        item = self.tableWidget_ProjectSettings.item(3, 0)
        item.setText(_translate("MainWindow", "impl_bitstream"))
        item = self.tableWidget_ProjectSettings.item(4, 0)
        item.setText(_translate("MainWindow", "boot_bitstream"))
        item = self.tableWidget_ProjectSettings.item(5, 0)
        item.setText(_translate("MainWindow", "zybo_path"))
        self.tableWidget_ProjectSettings.setSortingEnabled(__sortingEnabled)
        self.pushButton_5.setText(_translate("MainWindow", "SAVE Project Settings"))
        self.tableWidget_IpCores.setSortingEnabled(True)
        self.pushButton_8.setText(_translate("MainWindow", "Sync IP settings to Board"))
        self.pushButton.setText(_translate("MainWindow", "Update Bitstream"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("MainWindow", "Project"))
        self.label_PmodConn_1.setText(_translate("MainWindow", "TextLabel"))
        self.tableWidget_Board_Zybo.setSortingEnabled(True)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Zybo"))
        self.tableWidget_Board_Zybo_z7_10.setSortingEnabled(True)
        self.label_PmodConn_2.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Zybo-z7-10"))
        self.tableWidget_Board_Zybo_z7_20.setSortingEnabled(True)
        self.label_PmodConn_3.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "Zybo-z7-20"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "ZBerry-7007S"))
        self.label_logo_board.setText(_translate("MainWindow", "TextLabel"))
        self.label_logo_vivado.setText(_translate("MainWindow", "TextLabel"))
        self.label_logo_fpgawiz.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Board"))
        self.tableWidget_Signals0.setSortingEnabled(True)
        self.pushButton_7.setText(_translate("MainWindow", "Get Signals"))
        self.pushButton_2.setText(_translate("MainWindow", "Get Register"))
        self.label_4.setText(_translate("MainWindow", "select IP Core"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "SIGNALS"))
        self.label_logo.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_Dashboard.setTitle(_translate("MainWindow", "DASHBOARD"))
        self.groupBox_2.setTitle(_translate("MainWindow", "ADD Widgets"))
        self.pushButton_13.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton_9.setText(_translate("MainWindow", "LED"))
        self.pushButton_10.setText(_translate("MainWindow", "Numeric Display"))
        self.pushButton_14.setText(_translate("MainWindow", "Label"))
        self.pushButton_15.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_20.setText(_translate("MainWindow", "SpinBox"))
        self.pushButton_17.setText(_translate("MainWindow", "Dial"))
        self.pushButton_21.setText(_translate("MainWindow", "HSlider"))
        self.pushButton_16.setText(_translate("MainWindow", "VSlider"))
        self.pushButton_RemoveWidget.setText(_translate("MainWindow", "REMOVE"))
        self.pushButton_12.setText(_translate("MainWindow", "LOAD"))
        self.pushButton_11.setText(_translate("MainWindow", "SAVE"))
        self.pushButton_19.setText(_translate("MainWindow", "Print Signals"))
        self.pushButton_18.setText(_translate("MainWindow", "Signal Setting"))
        self.pushButton_22.setText(_translate("MainWindow", "LineEdit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "DashBoard"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_application), _translate("MainWindow", "APPLICATION"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuProject.setTitle(_translate("MainWindow", "Project"))
        self.menuBoard.setTitle(_translate("MainWindow", "Board"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCreate.setText(_translate("MainWindow", "Create"))
        self.actionConnect_Main_Server.setText(_translate("MainWindow", "Connect Main Server"))
        self.actionConnect_Aux_Server.setText(_translate("MainWindow", "Connect Aux Server"))
        self.actionStart_APU.setText(_translate("MainWindow", "Start APU"))
        self.actionStop_APU.setText(_translate("MainWindow", "Stop APU"))

