-- VHDL Entity common_lib_new.DualEncoder.symbol
--
-- Created:
--          by - Yoshi.UNKNOWN (YOSHIS-LAPTOP)
--          at - 15:22:05 23.03.2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity DualEncoder is
   generic( 
      nbits_g : integer := 4
   );
   port( 
      A1_in   : in     std_logic;
      A2_in   : in     std_logic;
      B1_in   : in     std_logic;
      B2_in   : in     std_logic;
      clk     : in     std_logic;
      res_btn : in     std_logic;
      LEDs    : out    std_logic_vector (3 downto 0)
   );

-- Declarations

end DualEncoder ;

--
-- VHDL Architecture common_lib_new.DualEncoder.struct
--
-- Created:
--          by - Yoshi.UNKNOWN (YOSHIS-LAPTOP)
--          at - 15:22:05 23.03.2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

library common_lib_new;

architecture struct of DualEncoder is

   -- Architecture declarations

   -- Internal signal declarations
   signal count  : std_logic_vector(nbits_g-1 downto 0);
   signal count1 : std_logic_vector(nbits_g-1 downto 0);
   signal reset  : std_logic;


   -- Component Declarations
   component Debouncer_EdgeDetection
   port (
      D        : in     std_logic ;
      clk      : in     std_logic ;
      Neg_Edge : out    std_logic ;
      Pos_Edge : out    std_logic ;
      Q        : out    std_logic 
   );
   end component;
   component Encoder
   generic (
      nbits_g : integer := 4
   );
   port (
      A_in  : in     std_logic ;
      B_in  : in     std_logic ;
      clk   : in     std_logic ;
      reset : in     std_logic ;
      count : out    std_logic_vector (nbits_g-1 downto 0)
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : Debouncer_EdgeDetection use entity common_lib_new.Debouncer_EdgeDetection;
   for all : Encoder use entity common_lib_new.Encoder;
   -- pragma synthesis_on


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   LEDs <= count or count1;
                                          


   -- Instance port mappings.
   U_2 : Debouncer_EdgeDetection
      port map (
         D        => res_btn,
         clk      => clk,
         Neg_Edge => open,
         Pos_Edge => open,
         Q        => reset
      );
   U_0 : Encoder
      generic map (
         nbits_g => 4
      )
      port map (
         A_in  => A1_in,
         B_in  => B1_in,
         clk   => clk,
         reset => reset,
         count => count
      );
   U_1 : Encoder
      generic map (
         nbits_g => 4
      )
      port map (
         A_in  => A2_in,
         B_in  => B2_in,
         clk   => clk,
         reset => reset,
         count => count1
      );

end struct;
