-- VHDL Entity common_lib_new.SoundGen.symbol
--
-- Created:
--          by - Yoshi.UNKNOWN (YOSHIS-LAPTOP)
--          at - 16:44:09 23.03.2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity SoundGen is
   port( 
      button : in     std_logic;
      clk    : in     std_logic;
      outH   : out    std_logic;
      outL   : out    std_logic
   );

-- Declarations

end SoundGen ;

--
-- VHDL Architecture common_lib_new.SoundGen.struct
--
-- Created:
--          by - Yoshi.UNKNOWN (YOSHIS-LAPTOP)
--          at - 16:44:09 23.03.2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

library common_lib_new;

architecture struct of SoundGen is

   -- Architecture declarations

   -- Internal signal declarations
   signal Pos_Edge : std_logic;
   signal output   : std_logic;


   -- Component Declarations
   component Debouncer_EdgeDetection
   port (
      D        : in     std_logic ;
      clk      : in     std_logic ;
      Neg_Edge : out    std_logic ;
      Pos_Edge : out    std_logic ;
      Q        : out    std_logic 
   );
   end component;
   component SquareGen
   generic (
      scaler : integer := 60000
   );
   port (
      active : in     std_logic ;
      outH   : out    std_logic ;
      outL   : out    std_logic ;
      clk    : in     std_logic 
   );
   end component;
   component toggle
   port (
      clk    : in     std_logic ;
      input  : in     std_logic ;
      output : out    std_logic 
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : Debouncer_EdgeDetection use entity common_lib_new.Debouncer_EdgeDetection;
   for all : SquareGen use entity common_lib_new.SquareGen;
   for all : toggle use entity common_lib_new.toggle;
   -- pragma synthesis_on


begin

   -- Instance port mappings.
   U_1 : Debouncer_EdgeDetection
      port map (
         D        => button,
         clk      => clk,
         Neg_Edge => open,
         Pos_Edge => Pos_Edge,
         Q        => open
      );
   U_0 : SquareGen
      port map (
         active => output,
         outH   => outH,
         outL   => outL,
         clk    => clk
      );
   U_2 : toggle
      port map (
         clk    => clk,
         input  => Pos_Edge,
         output => output
      );

end struct;
