-- VHDL Entity common_lib_new.TB_Debouncer.symbol
--
-- Created:
--          by - Yoshi.UNKNOWN (YOSHIS-LAPTOP)
--          at - 16:03:08 22.03.2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity TB_Debouncer is
-- Declarations

end TB_Debouncer ;

--
-- VHDL Architecture common_lib_new.TB_Debouncer.struct
--
-- Created:
--          by - Yoshi.UNKNOWN (YOSHIS-LAPTOP)
--          at - 11:56:38 23.03.2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

library common_lib;

architecture struct of TB_Debouncer is

   -- Architecture declarations

   -- Internal signal declarations
   signal D        : std_logic;
   signal Neg_Edge : std_logic;
   signal Pos_Edge : std_logic;
   signal Q        : std_logic;
   signal clk      : std_logic;


   -- Component Declarations
   component Debouncer_EdgeDetection
   port (
      D        : in     std_logic ;
      clk      : in     std_logic ;
      Neg_Edge : out    std_logic ;
      Pos_Edge : out    std_logic ;
      Q        : out    std_logic 
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : Debouncer_EdgeDetection use entity common_lib.Debouncer_EdgeDetection;
   -- pragma synthesis_on


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   --clk signal
   process
   begin
      clk <= '0';
      wait for 5 ns;
      clk <= '1';
      wait for 5 ns;
   end process;
   
   --D Signal
   process
   begin
      D <=  '0';
      wait for 54 ns;
      D <= '1';
      wait for 65 ns;
      D <= '0';
      wait for 26 ns;
      D <= '1';
      wait for 83 ns;
   end process;                                       


   -- Instance port mappings.
   U_0 : Debouncer_EdgeDetection
      port map (
         D        => D,
         clk      => clk,
         Neg_Edge => Neg_Edge,
         Pos_Edge => Pos_Edge,
         Q        => Q
      );

end struct;
