-- VHDL Entity common_lib_new.TBSquareGen.symbol
--
-- Created:
--          by - Yoshi.UNKNOWN (YOSHIS-LAPTOP)
--          at - 17:34:14 25.03.2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity TBSquareGen is
   port( 
      outH : out    std_logic;
      outL : out    std_logic
   );

-- Declarations

end TBSquareGen ;

--
-- VHDL Architecture common_lib_new.TBSquareGen.struct
--
-- Created:
--          by - Yoshi.UNKNOWN (YOSHIS-LAPTOP)
--          at - 17:34:14 25.03.2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
use ieee.numeric_std.all;

library common_lib_new;

architecture struct of TBSquareGen is

   -- Architecture declarations

   -- Internal signal declarations
   signal active : std_logic;
   signal clk    : std_logic;


   -- Component Declarations
   component SquareGen
   generic (
      scaler : integer := 120000
   );
   port (
      active : in     std_logic ;
      outH   : out    std_logic ;
      outL   : out    std_logic ;
      clk    : in     std_logic 
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : SquareGen use entity common_lib_new.SquareGen;
   -- pragma synthesis_on


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   process
   begin
   clk <= '1';
   wait for 5 ns;
   clk <= '0';
   wait for 5 ns;       
   end process;
   
   process
   begin
   active <= '1';
   wait for 10 ms;
   active <= '0';
   wait for 5 ms;
   end process;
                               


   -- Instance port mappings.
   U_0 : SquareGen
      port map (
         active => active,
         outH   => outH,
         outL   => outL,
         clk    => clk
      );

end struct;
