-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\AWFG_2022b\FPGA.vhd
-- Created: 2022-06-22 10:15:53
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2e-08
-- Target subsystem base rate: 2e-08
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        2e-08
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- WF                            ce_out        2e-08
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FPGA
-- Source Path: AWFG_2022b/FPGA
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.FPGA_pkg.ALL;

ENTITY FPGA IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        Write                             :   IN    std_logic;
        Addr                              :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        C0                                :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        C1                                :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        C2                                :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        C3                                :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        M                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        tper_cnt                          :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        Reset_HDL                         :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        frequency                         :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        amplitude                         :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        ce_out                            :   OUT   std_logic;
        WF                                :   OUT   std_logic_vector(31 DOWNTO 0)  -- int32
        );
END FPGA;

-- EMPTY MODEL

ARCHITECTURE rtl OF FPGA IS


BEGIN

  ce_out <= clk_enable;

END rtl;

