-- VHDL Entity sbus_awfg_lib.uart_top.symbol
--
-- Created:
--          by - Net.UNKNOWN (M00443)
--          at - 11:24:02 16.04.2012
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity uart_top is
   generic( 
      core_clk_freq_g : integer := 50000000;
      baudrate_g      : integer := 9600
   );
   port( 
      clk    : in     std_logic;
      din    : in     std_logic_vector (7 downto 0);
      reset  : in     std_logic;
      rxd    : in     std_logic;
      we     : in     std_logic;
      dout   : out    std_logic_vector (7 downto 0);
      rx_ack : out    std_logic;
      tx_ack : out    std_logic;                      -- transmit acknowledge
      txd    : out    std_logic
   );

-- Declarations

end uart_top ;

--
-- VHDL Architecture sbus_awfg_lib.uart_top.struct
--
-- Created:
--          by - Net.UNKNOWN (M00443)
--          at - 10:37:35 15.06.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

library sbus_awfg_lib;

architecture struct of uart_top is

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   component uart_rx
   generic (
      baudrate_g      : integer := 9600;
      core_clk_freq_g : integer := 50000000
   );
   port (
      clk    : in     std_logic ;
      reset  : in     std_logic ;
      rxd    : in     std_logic ;
      dout   : out    std_logic_vector (7 downto 0);
      rx_ack : out    std_logic 
   );
   end component;
   component uart_tx
   generic (
      baudrate_g      : integer := 9600;
      core_clk_freq_g : integer := 50000000
   );
   port (
      clk    : in     std_logic ;                    -- core clock
      din    : in     std_logic_vector (7 downto 0); -- parallel tx data input
      reset  : in     std_logic ;                    -- synchronous, active high reset
      we     : in     std_logic ;                    -- data write enable
      tx_ack : out    std_logic ;                    -- transmit acknowledge
      txd    : out    std_logic                      -- serial  transmit data
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : uart_rx use entity sbus_awfg_lib.uart_rx;
   for all : uart_tx use entity sbus_awfg_lib.uart_tx;
   -- pragma synthesis_on


begin

   -- Instance port mappings.
   I0 : uart_rx
      generic map (
         baudrate_g      => baudrate_g,
         core_clk_freq_g => core_clk_freq_g
      )
      port map (
         clk    => clk,
         reset  => reset,
         rxd    => rxd,
         dout   => dout,
         rx_ack => rx_ack
      );
   I1 : uart_tx
      generic map (
         baudrate_g      => baudrate_g,
         core_clk_freq_g => core_clk_freq_g
      )
      port map (
         clk    => clk,
         din    => din,
         reset  => reset,
         we     => we,
         tx_ack => tx_ack,
         txd    => txd
      );

end struct;
