-- VHDL Entity tutorial_lib.tb_top_counter.symbol
--
-- Created:
--          by - bauerjoh17.UNKNOWN (R00717)
--          at - 10:13:41 10/ 8/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity tb_top_counter is
-- Declarations

end tb_top_counter ;

--
-- VHDL Architecture tutorial_lib.tb_top_counter.struct
--
-- Created:
--          by - Yoshi.UNKNOWN (YOSHIS-LAPTOP)
--          at - 17:12:28 22.10.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

library tutorial_lib;

architecture struct of tb_top_counter is

   -- Architecture declarations

   -- Internal signal declarations
   signal buttons : std_logic_vector(3 downto 0);
   signal clk     : std_logic;
   signal leds    : std_logic_vector(3 downto 0);
   signal sliders : std_logic_vector(3 downto 0);


   -- Component Declarations
   component top_counter
   port (
      buttons : in     std_logic_vector (3 downto 0);
      clk     : in     std_logic ;
      sliders : in     std_logic_vector (3 downto 0);
      leds    : out    std_logic_vector (3 downto 0)
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : top_counter use entity tutorial_lib.top_counter;
   -- pragma synthesis_on


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- generate clock signal
   process
   begin
      clk <= '0' ;
      wait for 5 ns;
      clk <= '1' ;
      wait for 5 ns;
   end process;
   
   --generate button signals
   process
   begin
      buttons <= (others => '0');
      sliders <= (others => '0');
      sliders(0) <= '1';
      wait for 1 us;
      sliders(0) <= '0';
      wait for 1 us;
      sliders(1) <= '1';
      wait for 10 us;
      sliders(2) <= '1';
      wait;
   end process;                                     


   -- Instance port mappings.
   U_0 : top_counter
      port map (
         buttons => buttons,
         clk     => clk,
         sliders => sliders,
         leds    => leds
      );

end struct;
