set_property PACKAGE_PIN U12 [get_ports A2_in]
set_property PACKAGE_PIN Y14 [get_ports A1_in]
set_property PACKAGE_PIN W14 [get_ports B1_in]
set_property PACKAGE_PIN T12 [get_ports B2_in]
set_property PACKAGE_PIN L16 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports A1_in]
set_property IOSTANDARD LVCMOS33 [get_ports A2_in]
set_property IOSTANDARD LVCMOS33 [get_ports B1_in]
set_property IOSTANDARD LVCMOS33 [get_ports B2_in]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports res_btn]
set_property PACKAGE_PIN Y16 [get_ports res_btn]

set_property PACKAGE_PIN M14 [get_ports {LEDs[0]}]
set_property PACKAGE_PIN M15 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN G14 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN D18 [get_ports {LEDs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[0]}]

